---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 1e81cd3debfcea8befb92e80f5055d40628e6b43
    app.quarkus.io/build-timestamp: 2022-03-14 - 13:27:05 +0000
  labels:
    app.kubernetes.io/name: scheduler
    app.kubernetes.io/version: "1.0"
    app.openshift.io/runtime: quarkus
  name: scheduler
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: scheduler
    app.kubernetes.io/version: "1.0"
  type: ClusterIP
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app.kubernetes.io/name: scheduler
    app.kubernetes.io/version: "1.0"
  name: openjdk-11
spec:
  dockerImageRepository: registry.access.redhat.com/ubi8/openjdk-11
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 1e81cd3debfcea8befb92e80f5055d40628e6b43
    app.quarkus.io/build-timestamp: 2022-03-14 - 13:27:05 +0000
  labels:
    app.kubernetes.io/name: scheduler
    app.kubernetes.io/version: "1.0"
    app.openshift.io/runtime: quarkus
  name: scheduler
spec: {}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 1e81cd3debfcea8befb92e80f5055d40628e6b43
    app.quarkus.io/build-timestamp: 2022-03-14 - 13:27:05 +0000
  labels:
    app.kubernetes.io/name: scheduler
    app.kubernetes.io/version: "1.0"
    app.openshift.io/runtime: quarkus
  name: scheduler
spec:
  output:
    to:
      kind: ImageStreamTag
      name: scheduler:1.0
  source:
    binary: {}
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: openjdk-11:1.11
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 1e81cd3debfcea8befb92e80f5055d40628e6b43
    app.quarkus.io/build-timestamp: 2022-03-14 - 13:27:05 +0000
  labels:
    app.kubernetes.io/name: scheduler
    app.kubernetes.io/version: "1.0"
    app.openshift.io/runtime: quarkus
  name: scheduler
spec:
  replicas: 1
  selector:
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/name: scheduler
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-url: <<unknown>>
        app.quarkus.io/commit-id: 1e81cd3debfcea8befb92e80f5055d40628e6b43
        app.quarkus.io/build-timestamp: 2022-03-14 - 13:27:05 +0000
      labels:
        app.openshift.io/runtime: quarkus
        app.kubernetes.io/version: "1.0"
        app.kubernetes.io/name: scheduler
    spec:
      containers:
        - command:
            - java
            - -Dquarkus.http.host=0.0.0.0
            - -Djava.util.logging.manager=org.jboss.logmanager.LogManager
            - -jar
            - /deployments/quarkus-run.jar
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JAVA_APP_JAR
              value: /deployments/scheduler-1.0.0-SNAPSHOT-runner.jar
          image: image-registry.openshift-image-registry.svc:5000/msaday22/scheduler:1.0
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: scheduler
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - scheduler
        from:
          kind: ImageStreamTag
          name: scheduler:1.0
      type: ImageChange
---
apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: scheduler-my-db
spec:
  application:
    group: apps.openshift.io
    name: scheduler
    version: v1
    kind: DeploymentConfig
  services:
    - group: postgres-operator.crunchydata.com
      version: v1beta1
      kind: PostgresCluster
      name: 'hippo '
  detectBindingResources: false
  bindAsFiles: true
---
apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: scheduler-postgresql
spec:
  application:
    group: apps.openshift.io
    name: scheduler
    version: v1
    kind: DeploymentConfig
  services:
    - group: postgres-operator.crunchydata.com
      version: v1beta1
      kind: PostgresCluster
      name: postgresql
  detectBindingResources: false
  bindAsFiles: true
