name: build-deploy-to-openshift
on:
  push:
    branches:
    - main

jobs:
  build:
    name: "Source to container"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
  deploy:
