name: ci
on:
  push:
    branches:
    - main
jobs:
  build:
    name: "Source to container image"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: login-to-cluster
        name: login to cluster
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.API_SERVER }}
          openshift_username: ${{ secrets.USERNAME }}
          openshift_password: ${{ secrets.PASSWORD }}
          insecure_skip_tls_verify: true
      - run: ./mvnw clean package -Dquarkus.container-image.build=true

  deploy:
    name: "deploy to openshift"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - id: login-to-cluster
        name: login to cluster
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.API_SERVER }}
          openshift_username: ${{ secrets.USERNAME }}
          openshift_password: ${{ secrets.PASSWORD }}
          insecure_skip_tls_verify: true
      - run: helm upgrade -i scheduler ./deploy/k8s/helm/scheduler -f ./deploy/k8s/helm/scheduler/Values.yaml